rootProject.name = "blueprint"
include(":app")
include(":presentation:view")
include(":presentation:viewmodel")
include(":domain:repository")
include(":domain:model")
include(":domain:usecase")
include(":data:resource")
include(":data:repository")
include(":data:database")
include(":data:api")
include(":data:memory")
