[versions]
versionCode = "1"
versionName = "1.0.0"

compileSdk = "33"
minSdk = "28"
targetSdk = "33"
java = "11"

android-plugin = "7.4.2"
kotlin = "1.7.20"
dagger = "2.48.1"
compose-compiler = "1.3.2"
accompanist = "0.32.0"
distinations = "1.7.23-beta"

[libraries]
# Kotlinx Coroutines
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
# Kotlinx Serialization
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
# Kotlinx DateTime
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.1"
# AndroidX Compose BOM
androidx-compose-bom = "androidx.compose:compose-bom:2022.10.00"
# AndroidX Compose Preview support
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
# AndroidX Compose Material3
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
# AndroidX Compose Material Icons
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
# AndroidX Compose UI Test
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
# AndroidX Activity Compose
androidx-activity-compose = "androidx.activity:activity-compose:1.6.1"
# AndroidX Lifecycle Runtime Compose
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:2.6.2"
# AndroidX JUnit
androidx-junit = "androidx.test.ext:junit:1.1.5"
# Accompanist Swipe Refresh
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
# Accompanist System UI Controller
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
# Coil
coil-compose = "io.coil-kt:coil-compose:2.2.2"
# Dagger
dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
# Compose Distinations
compose-distinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "distinations" }
compose-distinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "distinations" }
# Ktor BOM
ktor-bom = "io.ktor:ktor-bom:2.1.3"
# Ktor Serialization
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
# Ktor Client CIO
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
# Ktor Client Content Negotiation
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
# Junit
junit = "junit:junit:4.13.2"
# Kotest
kotest-assertions-core = "io.kotest:kotest-assertions-core:5.5.3"

[plugins]
# Kotlin JVM
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
# Kotlin Android
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# Kotlin Kapt
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
# Kotlin Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# Android Gradle Plugin
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
# Dagger Hilt
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
# Google Ksp
google-ksp = { id = "com.google.devtools.ksp", version = "1.9.20-1.0.14" }
