[versions]
versionCode = "1"
versionName = "1.0.0"

compileSdk = "33"
minSdk = "28"
targetSdk = "33"
java = "11"

android-plugin = "7.2.2"
kotlin = "1.7.0"
dagger = "2.43.2"
lifecycle = "2.6.0-alpha01"
compose-compiler = "1.2.0"
compose-ui = "1.2.1"
compose-material = "1.2.1"
accompanist = "0.25.0"
storeflowable = "5.3.0"
distinations = "1.5.7-beta"

[libraries]
# Kotlinx Coroutines
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
# Kotlinx Serialization
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3"
# Kotlinx DateTime
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
# AndroidX Compose Runtime
androidx-compose-runtime = "androidx.compose.runtime:runtime:1.2.0"
# AndroidX Compose UI
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
# AndroidX Compose Tooling support
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
# AndroidX Compose Foundation
androidx-compose-fondation = "androidx.compose.foundation:foundation:1.2.1"
# AndroidX Compose Material3
androidx-compose-material3 = "androidx.compose.material3:material3:1.0.0-alpha16"
# AndroidX Compose Material Icons
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose-material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material" }
# AndroidX Compose UI Test
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
# AndroidX Activity Compose
androidx-activity-compose = "androidx.activity:activity-compose:1.5.1"
# AndroidX Navigation Compose
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.5.1"
# AndroidX Hilt Navigation Compose
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
# AndroidX Lifecycle Runtime Compose
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
# AndroidX Lifecycle ViewModel
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
# AndroidX JUnit
androidx-junit = "androidx.test.ext:junit:1.1.3"
# AndroidX Espresso
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
# Accompanist Swipe Refresh
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
# Accompanist System UI Controller
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
# Coil
coil-compose = "io.coil-kt:coil-compose:2.1.0"
# Dagger
dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
# Compose Distinations
compose-distinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "distinations" }
compose-distinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "distinations" }
# OkHttp
okhttp = "com.squareup.okhttp3:okhttp:4.10.0"
# Retrofit
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
# Retrofit Serialization Converter
retrofit-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
# StoreFlowable.kt
storeflowable = { module = "com.kazakago.storeflowable:storeflowable", version.ref = "storeflowable" }
storeflowable-core = { module = "com.kazakago.storeflowable:storeflowable-core", version.ref = "storeflowable" }
# Junit
junit = "junit:junit:4.13.2"
# Kotest
kotest-assertions-core = "io.kotest:kotest-assertions-core:5.4.1"

[plugins]
# Kotlin JVM
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
# Kotlin Android
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# Kotlin Kapt
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
# Kotlin Serialization
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# Android Gradle Plugin
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
# Dagger Hilt
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
# Google Ksp
google-ksp = { id = "com.google.devtools.ksp", version = "1.7.0-1.0.6" }
