name: DeployDevelop

on:
  push:
    branches: 
      - develop
      - release/*
      - hotfix/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build
      run: ./gradlew app:bundleDevelopRelease
    - name: Sign
      uses: mukeshsolanki/bundletool-action@v1.0.0
      with:
        aabFile: ./app/build/outputs/apk/develop/release/app-develop-release.aab
        base64Keystore: ${{ secrets.SIGNING_KEY_BASE64 }}
        keystorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        keystoreAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyPassword: ${{ secrets.SIGNING_KEY_ALIAS_PASSWORD }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: ${{ steps.convert_aab.outputs.apkPath }}
